server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: otp-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: mypassword
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/migrations/changelog-master.xml
  cloud:
    config:
      enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: talimul11bari@gmail.com
    password: sjsfgnasrwfrgrcv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    config-url:
  api-docs:
    path: /docs
